name: Why We Are Hunters
favicon: null
layout_spectrum: 0.2941751235630363
typography_spectrum: 0.6280267199035734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9141415250487626
  lightness: 0.23327821446582675
  saturation: 0.913950921734795
  rhythmicContrast: 0.49850775906816125
purpose: []
